- name: Get the security group for RDS instance
  amazon.aws.ec2_group_info:
    filters:
      "tag:Name": "{{tag_prefix}}-RDS-EC2-sg"
  register: sg_reg

- name: "Create a RDS instance with {{ db_engine }} database"
  community.aws.rds_instance:
    db_instance_identifier: "{{ db_instance_name }}"
    region: "{{ region }}"
    instance_type: "{{ db_instance_type }}"
    allocated_storage: "{{ db_storage }}"
    db_subnet_group_name: "{{ rds_subnet_group }}"
    vpc_security_group_ids:
      - "{{ sg_reg.security_groups[0].group_id }}"
    engine: "{{ db_engine }}"
    port: "{{ db_port }}"
    state: present
    master_username: "{{ db_master_user }}"
    master_user_password: "{{ db_master_pass }}"
    db_name: "{{ db_name }}"
    tags:
      Name: "{{ tag_prefix }}-{{ db_engine }}"
  register: rds_instance

- name: Store the database instance endpoint
  set_fact:
    db_endpoint: "{{ rds_instance.endpoint.address }}"
