- name: Create a shared folder for key to be stored for reusal
  ansible.builtin.file:
    path: "{{ playbook_dir }}/shared"
    state: directory
    mode: 0755

- name: Create the EC2 SSH key
  amazon.aws.ec2_key:
    name: ecom
  register: ec2_key

- name: Store the SSH key
  ansible.builtin.copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "{{ playbook_dir }}/shared/ec2_key.pem"
    mode: 0600
  when: ec2_key.changed

- name: Get host's current public IP address
  uri:
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_response

- name: Store the ip address for upcoming roles
  set_fact:
    ip_addr: "{{ ip_response.content }}"

