- name: Get the public subnet for NAT
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Name": "{{ tag_prefix }}-pub_subnet_a"
  register: subnet_reg

- import_tasks: setup_nat_sg.yml

- name: Create a NAT instance
  amazon.aws.ec2_instance:
    name: "{{ tag_prefix }}-nat"
    key_name: "{{ ec2_key_name }}"
    instance_type: "{{ ec2_instance_type }}"
    image_id: "{{ ec2_amazonlinux2_image_id }}"
    vpc_subnet_id: "{{ subnet_reg.subnets[0].id }}"
    security_group: "{{ nat_sg_reg.group_id }}"
    network:
      assign_public_ip: yes
    user_data: "{{ lookup('ansible.builtin.file', '../files/nat_user_data.sh') }}"
    tags:
      Role: NAT
    state: running
    wait: yes
  register: nat_reg

- name: Store NAT instance ID and public IP
  set_fact:
    nat_id: "{{ nat_reg.instances[0].instance_id }}"
    nat_ip: "{{ nat_reg.instances[0].public_ip_address }}"
