- name: Get the public subnet for NAT
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Name": "pub-subnet-a"
  register: subnet_reg

- name: Get the security group for NAT instance
  amazon.aws.ec2_group_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Name": "nat-sg"   
  register: sg_reg

- name: Create NAT instance
  amazon.aws.ec2_instance:
    name: nat_instance
    key_name: ecom
    vpc_subnet_id: "{{ subnet_reg.subnets[0].id }}"
    instance_type: t2.micro
    security_groups: "{{ sg_reg.security_groups[0].group_id }}"
    network:
      assign_public_ip: yes
    image_id: "{{ nat_instance_al2_image_id }}"
    tags:
      Name: nat_main
      Role: NAT
    state: running
    wait: yes
  register: nat_reg

- name: Store NAT instance ID
  set_fact:
    nat_id: "{{ nat_reg.instances[0].instance_id }}"
