- name: Create a public subnet A
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}a"
    cidr: "{{ pub_subnet_cidr.subnet_a }}"
    map_public: yes
    tags:
      Name: "{{ tag_prefix }}-pub_subnet_a"
  register: pub_subnet_a

- name: Create a public subnet B
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}b"
    cidr: "{{ pub_subnet_cidr.subnet_b }}"
    map_public: yes
    tags:
      Name: "{{ tag_prefix }}-pub_subnet_b"
  register: pub_subnet_b

- name: Create a public subnet C
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}c"
    cidr: "{{ pub_subnet_cidr.subnet_c }}"
    map_public: yes
    tags:
      Name: "{{ tag_prefix }}-pub_subnet_c"
  register: pub_subnet_c
