- name: Create a public subnet A
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}a"
    cidr: 10.0.0.0/24
    map_public: yes
    tags:
      Name: 'pub-subnet-a'
  register: pub_subnet_a

- name: Create a public subnet B
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}b"
    cidr: 10.0.1.0/24
    map_public: yes
    tags:
      Name: 'pub-subnet-b'
  register: pub_subnet_b

- name: Create a public subnet C
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}c"
    cidr: 10.0.2.0/24
    map_public: yes
    tags:
      Name: 'pub-subnet-c'
  register: pub_subnet_c
