- name: Create a private subnet A
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}a"
    cidr: "{{ pvt_subnet_cidr.subnet_a }}"
    map_public: no
    tags:
      Name: "{{ tag_prefix }}-pvt_subnet_a"
  register: pvt_subnet_a

- name: Create a private subnet B
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}b"
    cidr: "{{ pvt_subnet_cidr.subnet_b }}"
    map_public: no
    tags:
      Name: "{{ tag_prefix }}-pvt_subnet_b"
  register: pvt_subnet_b

- name: Create a private subnet C
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    az: "{{ region }}c"
    cidr: "{{ pvt_subnet_cidr.subnet_c }}"
    map_public: no
    tags:
      Name: "{{ tag_prefix }}-pvt_subnet_c"
  register: pvt_subnet_c

- name: Create a RDS subnet group
  community.aws.rds_subnet_group:
    state: present
    name: "{{ rds_subnet_group }}"
    description: RDS subnet group
    region: "{{ region }}"
    subnets:
      - "{{ pvt_subnet_a.subnet.id }}"
      - "{{ pvt_subnet_b.subnet.id }}"
      - "{{ pvt_subnet_c.subnet.id }}"
