ec2_amazonlinux2_image_id: ami-0ee415e1b8b71305f
nat_instance_al2_image_id: ami-037981e531e811c07
# Network vars
vpc_cidr: 10.0.0.0/16
pub_subnet_cidr:
  subnet_a: 10.0.0.0/24
  subnet_b: 10.0.1.0/24
  subnet_c: 10.0.2.0/24
pvt_subnet_cidr:
  subnet_a: 10.0.3.0/24
  subnet_b: 10.0.4.0/24
  subnet_c: 10.0.5.0/24
rds_subnet_group: "{{ app_name }}_RDS-EC2-subnets"
# Webserver vars
ws_instance_type: t2.micro
# RDS db vars
db_instance_name: "{{ app_name }}-db"
db_instance_type: db.t2.micro
db_storage: 20
db_engine: mariadb
db_port: 3306
db_name: ecomdb
db_master_user: admin
db_master_pass: "!p4$$w0rd"