- name: Create a security group for inbound traffic from EC2 to RDS
  amazon.aws.ec2_group:
    name: "{{ rds_ec2_sg_name }}"
    description: "{{ rds_ec2_sg_desc }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
          - "{{ rds_port }}"
        group_name: "{{ ec2_rds_sg_name }}"
        group_desc: "{{ ec2_rds_sg_desc }}"
        rule_desc: "{{ rds_ec2_rule_desc }}"
    rules_egress: []
    tags:
      Name: "{{ rds_ec2_sg_tag_name }}"
  register: sg_reg

- name: "Create a RDS instance with {{ db_engine }} database"
  community.aws.rds_instance:
    db_instance_identifier: "{{ db_instance_name }}"
    region: "{{ region }}"
    instance_type: "{{ db_instance_type }}"
    allocated_storage: "{{ db_storage }}"
    db_subnet_group_name: "{{ rds_subnet_group }}"
    vpc_security_group_ids:
      - "{{ sg_reg.group_id }}"
    engine: "{{ db_engine }}"
    port: "{{ db_port }}"
    state: present
    master_username: "{{ db_master_user }}"
    master_user_password: "{{ db_master_pass }}"
    db_name: "{{ db_name }}"
    tags:
      Name: "{{ tag_prefix }}-{{ db_engine }}"
