vpc_cidr: 10.0.0.0/16
pub_subnets:
  - az: "{{ region }}a"
    cidr: 10.0.0.0/24
    name: "{{ tag_prefix }}-pub_subnet_a"
  - az: "{{ region }}b"
    cidr: 10.0.1.0/24
    name: "{{ tag_prefix }}-pub_subnet_b"
  - az: "{{ region }}c"
    cidr: 10.0.2.0/24
    name: "{{ tag_prefix }}-pub_subnet_c"
pvt_subnets:
  - az: "{{ region }}a"
    cidr: 10.0.3.0/24
    name: "{{ tag_prefix }}-pvt_subnet_a"
  - az: "{{ region }}b"
    cidr: 10.0.4.0/24
    name: "{{ tag_prefix }}-pvt_subnet_b"
  - az: "{{ region }}c"
    cidr: 10.0.5.0/24
    name: "{{ tag_prefix }}-pvt_subnet_c"
rds_subnet_group: "{{ app_name }}_RDS-EC2-subnets"
