- name: Provision SSH and Security groups
  hosts: localhost
  connection: local
  tasks:
    - name: Create the EC2 SSH key
      amazon.aws.ec2_key:
        name: ansible_agent
      register: ec2_key

    - name: Create a shared folder for key to be stored for reusal
      file:
        path: ../../shared
        state: directory
        mode: 0755

    - name: Store the SSH key
      ansible.builtin.copy:
        content: '{{ ec2_key.key.private_key }}'
        dest: ../../shared/ec2_key.pem
        mode: 0600
      when: ec2_key.changed
    
    - name: Create Security Group for app instance
      amazon.aws.ec2_group:
        name: EC2 App Servers
        description: EC2 VPC Security Group for App Servers
        rules:
          - proto: tcp
            ports: 443
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow access to nginx from anywhere
          - proto: tcp
            ports: 8080
            cidr_ip: '{{ my_ip }}/32'
            rule_desc: Allow direct access from my IP
          - proto: tcp
            ports: 22
            cidr_ip: '{{ my_ip }}/32'
            rule_desc: Allow SSH access from my IP
      register: ec2_sg_app

    - name: Save Security Group ID to variables
      lineinfile:
        path: '{{ playbook_dir }}/group_vars/all/main.yml'
        regex: '^ec2_sg_app_id:'
        line: 'ec2_sg_app_id: {{ ec2_sg_app.group_id }}'
      when: ec2_sg_app.changed
