---
- name: Provision and deploy the eCommerce app on AWS
  hosts: localhost

  pre_tasks:
    - name: Get current public IP address
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response
  
    - name: Store current public IP address to variables
      lineinfile:
        path: "{{ playbook_dir }}/group_vars/all/main.yml"
        regex: '^my_ip:'
        line: "my_ip: {{ ip_response.content }}"

  roles:
    - network_setup