---
- name: Setup the backbone infrastructure
  hosts: localhost
  connection: local
  roles:
    - common
    - vpc
    - nat
    - routing
    - database
    - webservers

# TODO: Doesn't work now; Figure out SSM connection to the webserver instance
- name: Test SSM connection to webserver
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: "{{ aws_ssm_bucket_name }}"
    ansible_aws_ssm_region: "{{ region }}"
  tasks:
    - name: Say hello
      raw: echo "Hello World from $HOSTNAME!"

