- name: Provision an EC2 instance for web server
  hosts: localhost
  connection: local
  tasks:
    - name: Create instance
      amazon.aws.ec2_instance:
        name: Node_1
        key_name: 'webapp'
        instance_type: t2.micro
        security_group: '{{ ec2_sg_app_id }}'
        network:
          assign_public_ip: true
        image_id: '{{ ec2_amazonlinux2_image_id }}'
        tags:
          Purpose: Webserver
        wait: yes
      register: webserver_instance
    
    - name: Store instance public DNS to variables
      lineinfile:
        path: '{{ playbook_dir }}/group_vars/all/hosts.yml'
        regex: '^web_server_dns:'
        line: 'web_server_dns: {{ webserver_instance.instances[0].public_dns_name }}'